---
# tasks file for EC2
- name: Provision EC2 instance
  ec2:
     key_name: "{{ keypair }}" 
     instance_type: t2.micro
     image: ami-09558250a3419e7d0
     region: us-east-2
     group_id: sg-0cf1310e67515f6f9
     count: 1
     vpc_subnet_id: subnet-0076cb001eb5a9f6b
     assign_public_ip: yes
     instance_tags:
       Name: Jenkins
     wait_timeout: 60
...
